export enum EntityTable {
  WORKORDER = 'WORKORDER',
  SPAREPART = 'SPAREPART',
  SECTION = 'SECTION',
  OPERATOR = 'OPERATOR',
  PREVENTIVE = 'PEVENTIVE',
  INSPECTIONPOINTS = 'INSPECTIONPOINTS',
  MACHINE = 'MACHINE',
  ASSET = 'ASSET',
  USERS = 'USERS',
  DOWNTIMEREASONS = 'DOWNTIMEREASONS',
  DOWNTIMEREPORT = 'DOWNTIMEREPORT',
}
